version: '3.8'

services:
  web:
    build: .
    ports:
      - "8000:8000"
    environment:
      - FLASK_ENV=production
      - DB_HOST=rm-bp153zvpu95372h5f1o.mysql.rds.aliyuncs.com  # 阿里云RDS地址
      - DB_PORT=3306
      - DB_NAME=customs
      - DB_USER=ian_001
      - DB_PASSWORD=Eric1208
    volumes:
      - ./instance:/app/instance  # 持久化数据库
    deploy:
      resources:
        limits:
          cpus: '2'
          memory: 1G
    restart: always